[package]
name = "hiven"
version = "0.1.0"
edition = "2021"
authors = ["Nebula<nebula@kora.gg>"]
description = "Ephemeral Linux CLI to run quick commands"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
